### ISSUE TITLE
Etna Auth should use ParseBody to get all the params

### ISSUE THREAD

**Issue by coleshaw** [mountetna/etna#42]
Currently for POST requests, any supplied URL query parameters do not appear in `rack.request.params`. This means that for HMAC signature verification to work, those parameters have to be hacked into the request body. We would prefer to keep the signing params in the URL.

We should be able to use `Etna::ParseBody` to get all the params, regardless of where they are located. The `Etna::Auth` should use that implementation.

**Comment by graft** [comment]
Etna::ParseBody is a Rack layer that usually runs before Etna::Auth, e.g.:
https://github.com/mountetna/metis/blob/d32d9defcf13aaa8e58193e85badef8bf16e3cd0/config.ru#L10-L17

I.e., ParseBody will automatically stuff things into rack.request.params from wherever they might originate before Etna::Auth runs, allowing the latter to get whatever it needs from params. If params aren't showing up there is perhaps some other explanation.

**Comment by coleshaw** [comment]
Superceded by #43 -- I figured out the root cause for the query param issues I was seeing in Magma - Metis.
