### ISSUE TITLE
Bug in usage of persistent connections and query params

### ISSUE THREAD

**Issue by coleshaw** [mountetna/etna#43]
Per this [issue for the net::http::persistent library](https://github.com/drbrain/net-http-persistent/issues/35), if you use `uri.path` when constructing a persistent HTTP connection, it loses the query parameters. So we should update the `query_request` method to call `uri.request_uri` instead of `uri.path` when constructing the persistent connection.

**Comment by graft** [comment]
One option is to replace `net-http-persistent`, which is maybe not necessary with modern Ruby. At least according to [Net::HTTP docs](https://ruby-doc.org/stdlib-2.5.7/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-How+to+use+Net-3A-3AHTTP) connection reuse is straightforward with the Ruby stdlib. The interface is a little different, but I have made a client using the stdlib in the [metis_client](https://github.com/mountetna/metis/tree/graft-metis-client/); the same could be done here.

**Comment by coleshaw** [comment]
I do have this working in a local branch (I think), if we want to keep that library...

**Comment by graft** [comment]
Let's make the proximate fix (yours) since it will make the magma copy request less kludgy, in the future we can move the stuff from metis_client into here and shed the dependency.
